//Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
//Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//Flashcard
export const ADD_FLASHCARD = 'ADD_FLASHCARD';
export const DELETE_FLASHCARD = 'DELETE_FLASHCARD';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_FLASHCARD = 'UPDATE_FLASHCARD';
export const FILTER_FLASHCARDS = 'FILTER_FLASHCARDS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const FLASHCARD_ERROR = 'FLASHCARD_ERROR';
export const GET_FLASHCARDS = 'GET_FLASHCARDS';
export const CLEAR_FLASHCARDS = 'CLEAR_FLASHCARDS';
export const GET_SET_FLASHCARDS = 'GET_SET_FLASHCARDS';
//Marked flashcards
export const MARK_FLASHCARD = 'MARK_FLASHCARDS';
export const UNMARK_FLASHCARD = 'UNMARK_FLASHCARD';
export const CLEAR_MARKED = 'CLEAR_MARKED';
export const SET_MARKED = 'SET_MARKED';
//Sets
export const ADD_SET = 'ADD_SET';
export const DELETE_SET = 'DELETE_SET';
export const SET_CURRENT_SET = 'SET_CURRENT_SET';
export const CLEAR_CURRENT_SET = 'CLEAR_CURRENT_SET';
export const UPDATE_SET = 'UPDATE_SET';
export const SET_ERROR = 'SET_ERROR';
export const GET_MY_SETS = 'GET_MY_SETS';
export const GET_ALL_SETS = 'GET_ALL_SETS';
export const CLEAR_SETS = 'CLEAR_SETS';
export const FILTER_SETS = 'FILTER_SETS';
export const CLEAR_SET_FILTER = 'CLEAR_SET_FILTER';
//Subscription
export const SUBSCRIBE_TO_SET = 'SUBSCRIBE_TO_SET';
export const UNSUBSCRIBE_SET = 'UNSUBSCRIBE_SET';
export const SUBSCRIPTION_ERROR = 'SUBSCRIPTION_ERROR';
export const GET_MY_SUBSCRIPTIONS = 'GET_MY_SUBSCRIPTIONS';
export const SET_CURRENT_SUB_ID = 'SET_CURRENT_SUB_ID';
export const CLEAR_CURRENT_SUB_ID = 'SET_CURRENT_SUB_ID';
export const GET_SUBSCRIPTIONS_FOR_SET = 'GET_SUBSCRIPTIONS_FOR_SET';
export const CLEAR_SUBSCRIPTIONS = 'CLEAR_SUBSCRIPTIONS';
//Study
export const GET_STUDY_SESSION = 'GET_STUDY_SESSION';
export const GET_SESSION_TEST_RESULTS = 'GET_SESSION_TEST_RESULTS';
export const CLEAR_STUDY_SESSION = 'CLEAR_STUDY_SESSION';
export const STUDY_SESSION_ERROR = 'STUDY_SESSION_ERROR';
export const CLEAR_TEST_RESULTS = 'CLEAR_TEST_RESULTS';
export const GET_FINAL_TEST = 'GET_FINAL_TEST';
export const GET_FINAL_TEST_RESULTS = 'GET_FINAL_TEST_RESULTS';
export const CLEAR_FINAL_TEST = 'CLEAR_FINAL_TEST';